### ISSUE TITLE
DooH Application with impression tracker

### ISSUE THREAD

**Issue by vpetersson** [Screenly/Playground#39]
## Background

The idea with this is to showcase how to build an Digital Out of Home (DooH) platform for Screenly. The demo would be a simple Edge App app that randomly picks an image to return from a dataset (included in the Edge App). When the image is served, the app would take noticed of this and generate an event that is sent to Google Analytics.

The user will then be able to track the impressions directly in Google Analytics. We would also enrich this data with all the data available from the Screenly Metadata. That way you can not only see aggregates, but also slice it multiple ways (city etc).

## Acceptance Criteria

- [ ] Select 20 nice looking fake ads
- [ ] Write a simple Edge App in in JavaScript that perform the above operation
- [ ] Integrate the deployment with GitHub Actions

**Comment by vpetersson** [comment]
Somewhat already resolved with the QR Code Edge App.

**Comment by salmanfarisvp** [comment]
Moved to Edge App List
